In [1]:
LEFT = "58-59_bertrand_HotelSoissons"
RIGHT = "58-59_stephane_HotelSoissons"

In [2]:
!soffice --convert-to csv:"Text - txt - csv (StarCalc)":44,34,76 --headless ${LEFT}.ods
!soffice --convert-to csv:"Text - txt - csv (StarCalc)":44,34,76 --headless ${RIGHT}.ods
!diff 5${LEFT}.csv 5${RIGHT}.csv

5c5
< HôtelSoissons,78,10,0,78,40,0
---
> Hôtel de Soissons,78,40,0,78,40,0
8,9c8,9
< Hôtel Soissons,96,32,0,93,32,0
< Notre Dame,77,48,15,77,48,15
---
> Hôtel de Soissons,96,32,0,96,32,0
> Notre-Dame,77,48,15,77,48,15
11c11
< Hôtel Soissons,50,36,0,50,36,0
---
> Hôtel de Soissons,50,36,0,50,36,0
13,14c13,14
< Notre Dame,129,49,45,129,49,45
< Hôtel Soissons,32,44,0,32,44,0
---
> Notre-Dame,129,49,45,129,49,45
> Hôtel de Soissons,32,44,0,32,44,0
17c17
< Hôtel Soissons,17,52,0,17,52,0
---
> Hôtel de Soissons,17,52,0,17,52,0

In [3]:
import pandas as pd


a = pd.read_excel(f"{LEFT}.ods", engine="odf", header=(0,1))
b = pd.read_excel(f"{RIGHT}.ods", engine="odf", header=(0,1))

In [4]:

from IPython.display import display_html 

v = pd.DataFrame(a != b).applymap(lambda x: "background:red" if x != 0 else "")

to_side = lambda tbl : tbl.style.apply(lambda s: v, axis=None).set_table_attributes("style='display:inline'")

a =  to_side(a).set_caption(LEFT.upper())
b = to_side(b).set_caption(RIGHT.upper())

display_html(a._repr_html_()+b._repr_html_(), raw=True)