In [1]:
import pandas as pd 
import os

# Tous les angles aux sommets
sommets = pd.read_csv("toutes_les_bases.csv",header=[0,1], index_col=[0,1])

# Somme des angles des triangles, relevées dans le mémoire
total = pd.read_csv("angles_totaux.csv",header=[0,1], index_col=0)

In [2]:
def dms2dec(d=0, m=0, s=0):
    return d + m/60 + s/3600

def dec2dms(dec=0):
    deg = int(dec)
    mins = (dec - deg)*60
    secs = (mins - int(mins))*60
    return deg, int(mins), secs


columns = sommets.columns.levels[0]
cols2dec = lambda row: {columns[0]:dms2dec(*row[0:3]), columns[1]:dms2dec(*row[3:6])}

# Angles aux sommets en degrés décimaux
sommets_dec = sommets.apply(cols2dec, axis=1,  result_type='expand')

                        # Sommes des angles en degrés décimaux
total_dec = total.apply(cols2dec, axis=1,  result_type='expand')

In [3]:
actual = sommets_dec.reset_index()
actual = actual.groupby(actual.index // 3).sum()

# Sommes des angles aux sommets
actual.apply(lambda x: dec2dms(x[0]) + dec2dms(x[1]), axis=1,  result_type='expand')

        0     1     2      3     4             5
0   180.0   1.0   1.0  180.0   0.0  1.000000e+00
1   180.0   0.0  33.0  180.0   0.0  3.300000e+01
2   180.0   0.0  10.0  179.0  59.0  1.000000e+01
3   180.0   0.0  26.0  180.0   0.0  2.600000e+01
4   180.0   0.0  34.0  179.0  58.0  3.400000e+01
5   179.0  59.0  31.0  179.0  59.0  1.000000e+00
6   179.0  59.0  59.0  179.0  58.0  5.900000e+01
7   179.0  59.0  30.0  179.0  59.0  5.456968e-11
8   179.0  58.0   7.0  179.0  58.0  7.000000e+00
9   179.0  59.0  19.0  179.0  58.0  4.900000e+01
10  179.0  59.0  59.0  179.0  59.0  5.900000e+01
11  179.0  59.0  15.0  179.0  59.0  1.500000e+01
12  180.0   0.0  43.0  180.0   0.0  1.300000e+01
13  180.0   1.0  24.0  180.0   0.0  4.400000e+01
14  180.0   0.0  10.0  180.0   0.0  1.000000e+01
15  179.0  59.0  12.0  179.0  57.0  4.200000e+01
16  180.0   0.0  20.0  180.0   0.0  1.000000e+01
17  180.0   0.0   2.0  179.0  59.0  5.200000e+01
18  180.0   1.0  20.0  180.0   2.0  1.000000e+01

In [5]:
import numpy as np

expected = total_dec.reset_index()
diff = actual - expected
diff[np.abs(diff) < 10**-13] = 0 # Force les très petites valeurs à 0 
test = (diff == 0).all()
assert test["angles augmentés"] == True and test["angles observés"] == True